package com.dong.demo.domain;

import java.math.BigDecimal;

public class EcGoodsSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_ID
     *
     * @mbggenerated
     */
    private BigDecimal skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    private BigDecimal goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_PROP_ID_LIST
     *
     * @mbggenerated
     */
    private String skuPropIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_STOCK_QTY
     *
     * @mbggenerated
     */
    private Long skuStockQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_ICON_URL
     *
     * @mbggenerated
     */
    private String skuIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_NO
     *
     * @mbggenerated
     */
    private String skuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    private String skuPropTextList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal skuWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.SKU_VOLUMN
     *
     * @mbggenerated
     */
    private BigDecimal skuVolumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.MATERIAL_NO
     *
     * @mbggenerated
     */
    private String materialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_GOODS_SKU.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_ID
     *
     * @return the value of EC_GOODS_SKU.SKU_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_ID
     *
     * @param skuId the value for EC_GOODS_SKU.SKU_ID
     *
     * @mbggenerated
     */
    public void setSkuId(BigDecimal skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.GOODS_ID
     *
     * @return the value of EC_GOODS_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.GOODS_ID
     *
     * @param goodsId the value for EC_GOODS_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(BigDecimal goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_PROP_ID_LIST
     *
     * @return the value of EC_GOODS_SKU.SKU_PROP_ID_LIST
     *
     * @mbggenerated
     */
    public String getSkuPropIdList() {
        return skuPropIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_PROP_ID_LIST
     *
     * @param skuPropIdList the value for EC_GOODS_SKU.SKU_PROP_ID_LIST
     *
     * @mbggenerated
     */
    public void setSkuPropIdList(String skuPropIdList) {
        this.skuPropIdList = skuPropIdList == null ? null : skuPropIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_PRICE
     *
     * @return the value of EC_GOODS_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_PRICE
     *
     * @param skuPrice the value for EC_GOODS_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    public void setSkuPrice(BigDecimal skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_STOCK_QTY
     *
     * @return the value of EC_GOODS_SKU.SKU_STOCK_QTY
     *
     * @mbggenerated
     */
    public Long getSkuStockQty() {
        return skuStockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_STOCK_QTY
     *
     * @param skuStockQty the value for EC_GOODS_SKU.SKU_STOCK_QTY
     *
     * @mbggenerated
     */
    public void setSkuStockQty(Long skuStockQty) {
        this.skuStockQty = skuStockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_ICON_URL
     *
     * @return the value of EC_GOODS_SKU.SKU_ICON_URL
     *
     * @mbggenerated
     */
    public String getSkuIconUrl() {
        return skuIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_ICON_URL
     *
     * @param skuIconUrl the value for EC_GOODS_SKU.SKU_ICON_URL
     *
     * @mbggenerated
     */
    public void setSkuIconUrl(String skuIconUrl) {
        this.skuIconUrl = skuIconUrl == null ? null : skuIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_NO
     *
     * @return the value of EC_GOODS_SKU.SKU_NO
     *
     * @mbggenerated
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_NO
     *
     * @param skuNo the value for EC_GOODS_SKU.SKU_NO
     *
     * @mbggenerated
     */
    public void setSkuNo(String skuNo) {
        this.skuNo = skuNo == null ? null : skuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_NAME
     *
     * @return the value of EC_GOODS_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_NAME
     *
     * @param skuName the value for EC_GOODS_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_PROP_TEXT_LIST
     *
     * @return the value of EC_GOODS_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    public String getSkuPropTextList() {
        return skuPropTextList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_PROP_TEXT_LIST
     *
     * @param skuPropTextList the value for EC_GOODS_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    public void setSkuPropTextList(String skuPropTextList) {
        this.skuPropTextList = skuPropTextList == null ? null : skuPropTextList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_WEIGHT
     *
     * @return the value of EC_GOODS_SKU.SKU_WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getSkuWeight() {
        return skuWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_WEIGHT
     *
     * @param skuWeight the value for EC_GOODS_SKU.SKU_WEIGHT
     *
     * @mbggenerated
     */
    public void setSkuWeight(BigDecimal skuWeight) {
        this.skuWeight = skuWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.SKU_VOLUMN
     *
     * @return the value of EC_GOODS_SKU.SKU_VOLUMN
     *
     * @mbggenerated
     */
    public BigDecimal getSkuVolumn() {
        return skuVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.SKU_VOLUMN
     *
     * @param skuVolumn the value for EC_GOODS_SKU.SKU_VOLUMN
     *
     * @mbggenerated
     */
    public void setSkuVolumn(BigDecimal skuVolumn) {
        this.skuVolumn = skuVolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.MATERIAL_NO
     *
     * @return the value of EC_GOODS_SKU.MATERIAL_NO
     *
     * @mbggenerated
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.MATERIAL_NO
     *
     * @param materialNo the value for EC_GOODS_SKU.MATERIAL_NO
     *
     * @mbggenerated
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_GOODS_SKU.MODEL_NO
     *
     * @return the value of EC_GOODS_SKU.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_GOODS_SKU.MODEL_NO
     *
     * @param modelNo the value for EC_GOODS_SKU.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }
}