package com.dong.demo.domain;

import java.math.BigDecimal;

public class EcOrderSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.ORDER_SKU_ID
     *
     * @mbggenerated
     */
    private BigDecimal orderSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.ORDER_ID
     *
     * @mbggenerated
     */
    private BigDecimal orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.SKU_ID
     *
     * @mbggenerated
     */
    private BigDecimal skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.BUY_QTY
     *
     * @mbggenerated
     */
    private Long buyQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.BUY_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    private String skuPropTextList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    private BigDecimal goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.PROMO_LAUNCHER
     *
     * @mbggenerated
     */
    private Long promoLauncher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_ORDER_SKU.PROMO_ID
     *
     * @mbggenerated
     */
    private BigDecimal promoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.ORDER_SKU_ID
     *
     * @return the value of EC_ORDER_SKU.ORDER_SKU_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderSkuId() {
        return orderSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.ORDER_SKU_ID
     *
     * @param orderSkuId the value for EC_ORDER_SKU.ORDER_SKU_ID
     *
     * @mbggenerated
     */
    public void setOrderSkuId(BigDecimal orderSkuId) {
        this.orderSkuId = orderSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.ORDER_ID
     *
     * @return the value of EC_ORDER_SKU.ORDER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.ORDER_ID
     *
     * @param orderId the value for EC_ORDER_SKU.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.SKU_ID
     *
     * @return the value of EC_ORDER_SKU.SKU_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.SKU_ID
     *
     * @param skuId the value for EC_ORDER_SKU.SKU_ID
     *
     * @mbggenerated
     */
    public void setSkuId(BigDecimal skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.SKU_NAME
     *
     * @return the value of EC_ORDER_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.SKU_NAME
     *
     * @param skuName the value for EC_ORDER_SKU.SKU_NAME
     *
     * @mbggenerated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.BUY_QTY
     *
     * @return the value of EC_ORDER_SKU.BUY_QTY
     *
     * @mbggenerated
     */
    public Long getBuyQty() {
        return buyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.BUY_QTY
     *
     * @param buyQty the value for EC_ORDER_SKU.BUY_QTY
     *
     * @mbggenerated
     */
    public void setBuyQty(Long buyQty) {
        this.buyQty = buyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.BUY_PRICE
     *
     * @return the value of EC_ORDER_SKU.BUY_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.BUY_PRICE
     *
     * @param buyPrice the value for EC_ORDER_SKU.BUY_PRICE
     *
     * @mbggenerated
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.SKU_PROP_TEXT_LIST
     *
     * @return the value of EC_ORDER_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    public String getSkuPropTextList() {
        return skuPropTextList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.SKU_PROP_TEXT_LIST
     *
     * @param skuPropTextList the value for EC_ORDER_SKU.SKU_PROP_TEXT_LIST
     *
     * @mbggenerated
     */
    public void setSkuPropTextList(String skuPropTextList) {
        this.skuPropTextList = skuPropTextList == null ? null : skuPropTextList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.GOODS_ID
     *
     * @return the value of EC_ORDER_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.GOODS_ID
     *
     * @param goodsId the value for EC_ORDER_SKU.GOODS_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(BigDecimal goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.SKU_PRICE
     *
     * @return the value of EC_ORDER_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.SKU_PRICE
     *
     * @param skuPrice the value for EC_ORDER_SKU.SKU_PRICE
     *
     * @mbggenerated
     */
    public void setSkuPrice(BigDecimal skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.PROMO_LAUNCHER
     *
     * @return the value of EC_ORDER_SKU.PROMO_LAUNCHER
     *
     * @mbggenerated
     */
    public Long getPromoLauncher() {
        return promoLauncher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.PROMO_LAUNCHER
     *
     * @param promoLauncher the value for EC_ORDER_SKU.PROMO_LAUNCHER
     *
     * @mbggenerated
     */
    public void setPromoLauncher(Long promoLauncher) {
        this.promoLauncher = promoLauncher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_ORDER_SKU.PROMO_ID
     *
     * @return the value of EC_ORDER_SKU.PROMO_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_ORDER_SKU.PROMO_ID
     *
     * @param promoId the value for EC_ORDER_SKU.PROMO_ID
     *
     * @mbggenerated
     */
    public void setPromoId(BigDecimal promoId) {
        this.promoId = promoId;
    }
}