package com.dong.demo.mapper;

import com.dong.demo.domain.EcGoodsSku;
import java.math.BigDecimal;

public interface EcGoodsSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    int insert(EcGoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    int insertSelective(EcGoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    EcGoodsSku selectByPrimaryKey(BigDecimal skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EcGoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_GOODS_SKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcGoodsSku record);
}