package com.dong.demo.mapper;

import com.dong.demo.domain.EcOrderSku;
import java.math.BigDecimal;

public interface EcOrderSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal orderSkuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    int insert(EcOrderSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    int insertSelective(EcOrderSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    EcOrderSku selectByPrimaryKey(BigDecimal orderSkuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EcOrderSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_ORDER_SKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcOrderSku record);
}