spring:
  profiles:
    active: dev

  #数据源 HiKari无需配置durid
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.1.1.8:1433;Databasename=xcmgofficialdata
    username: sa
    password: xcmg#@!~
  #thymeleaf模板
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: /static/**
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dong.demo.domain

#pagehelper分页插件配置
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#日志配置
ogging:
  config: src/main/resources/logback.xml