server:
  servlet:
    context-path: /love1
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/love?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1234

#常量
boy:
  name: rose
  age: 22
  sex: female